### DISCUSSION TITLE
实在搞不定了，求助各位：除宿主机外其他设备无法访问容器的开放端口

### DISCUSSION THREAD

**Discussion by LisonFan** [docker-easyconnect/docker-easyconnect#254] [General]
同样的 docker-compose.yaml，在 Mac 上运行是没问题的，但是在虚拟机（RockyLinux）就不行，只能本地访问

在虚拟机（RockyLinux）中，我把 Firewalld 和 SELinux 都关了，也不知道是什么姿势不对

虚拟机（RockyLinux）内核版本是`5.14.0-284.11.1.el9_2.x86_64`

`netstat -ntlp`
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      776/sshd: /usr/sbin
tcp        0      0 0.0.0.0:41080           0.0.0.0:*               LISTEN      1191/docker-proxy
tcp        0      0 0.0.0.0:48888           0.0.0.0:*               LISTEN      1168/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      776/sshd: /usr/sbin
tcp6       0      0 :::41080                :::*                    LISTEN      1197/docker-proxy
tcp6       0      0 :::48888                :::*                    LISTEN      1174/docker-proxy
```

`iptables -L -n -v`
```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  181 78196 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  181 78196 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   78 67550 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
  103 10646 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:8888
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:1080

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
  103 10646 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
  181 78196 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
  103 10646 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
  181 78196 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

`docker-compose.yaml`
```
version: '3'

services:
  company:
    image: hagb/docker-easyconnect:cli
    restart: always
    network_mode: bridge
    container_name: easyconnect
    environment:
      - CLI_OPTS=-d https://vpn.com:12345/ -u username -p "password"
      - EC_VER=7.6.7
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    ports:
      - 41080:1080
      - 48888:8888
    volumes:
      - ecdata:/root

volumes:
  ecdata:
```
