### ISSUE TITLE
使用命令行直接运行可以连上，但使用docker-compose始终无法连接

### ISSUE THREAD

**Issue by paulzhn** [docker-easyconnect/docker-easyconnect#269]
我的命令行：

```
docker run -d --device /dev/net/tun --cap-add NET_ADMIN -ti -p 127.0.0.1:1080:1080 -p 127.0.0.1:8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d https://**.edu.cn -u *** -p ***" hagb/docker-easyconnect:cli
```

我的docker-compose.yml:

```
version: '2'
services:
    easyconnect:
        image: hagb/docker-easyconnect:cli # latest, vncless, 7.6.3, vncless-7.6.3, 7.6.7, vncless-7.6.7
        devices:
#          - /dev/dri
          - /dev/net/tun
        cap_add:
          - NET_ADMIN
#        volumes:
#          - /tmp/.X11-unix:/tmp/.X11-unix
#          - $HOME/.Xauthority:/root/.Xauthority
#          - $HOME/.ecdata:/root
        environment:
          - EC_VER=7.6.3
          - CLI_OPTS="-d https://***.edu.cn -u *** -p ***"
        ports:
          - "127.0.0.1:1081:1080"
          - "127.0.0.1:8888:8888"
 ```

失败提示：
```
easyconnect_1  | WARNING: logging deactivated (can't log to stdout when daemonized)
easyconnect_1  | auto login is disabled
easyconnect_1  | auth failed, please check if the vpn address is valid and reachable!
easyconnect_1  | login failed!
easyconnect_1  | svpn stop!
```

非常好奇这是什么原因，感谢作者！
