### ISSUE TITLE
图形界面版登录信息持久化似乎不起作用

### ISSUE THREAD

**Issue by Yusoo** [docker-easyconnect/docker-easyconnect#334]
使用最新`hagb/docker-easyconnect:7.6.7`镜像，在docker-compose中也配置了

```
 volumes:
      - ./easyconnect/:/root/
```

easyconnect目录下也有文件生成，但是只要把容器停了再启动，就会重新回到同意协议那个界面，vpn地址也要重新填。

**Comment by Einskai** [comment]
是怎么启动的呀？

**Comment by Yusoo** [comment]
```
services:
  easyconnect:
    image: hagb/docker-easyconnect:7.6.7
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./easyconnect/:/root/
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - USE_NOVNC=1
      - PASSWORD=***
```
docker-compose up -d 启动的
