### ISSUE TITLE
请教下为什么似乎只能访问网页，mysql这种应用程序访问不通 ，Tun模式

### ISSUE THREAD

**Issue by git-syl** [docker-easyconnect/docker-easyconnect#349]
遇到一个很奇怪的问题，想请问一下。
大致情况是：
Tun模式访问网页是可以的
http://192.168.0.35

但是访问应用mysql应用（192.168.0.115:33306）就会连接不上，idea里面提示 Connection refused: connect
Navicat也是类似的提示，用Navicat代理配置填入socks5 127.0.0.1和1080也不行。

随后，我用python跑了一下连接 mysql端口代码和网页。
response = requests.get('http://192.168.0.115:33306', proxies={'http': 'socks5://127.0.0.1:1080'})
有返回：requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('I\x00\x00\x00\n'))
网页80是正常html通的。
所以socks5应该是通的，一时间不知怎么找问题了。

开启Clash下：
```
ainsc>  route print
===========================================================================
接口列表
 49...........................Meta Tunnel
 18...00 ff 5f 5f 72 2e ......Sangfor SSL VPN CS Support System VNIC
 25...f8 89 d2 7e 26 37 ......Hyper-V Virtual Ethernet Adapter #3
 15...f8 89 d2 7e 26 37 ......Hyper-V Virtual Ethernet Adapter #4
 26...fa 89 d2 7e 26 27 ......Microsoft Wi-Fi Direct Virtual Adapter
 27...fa 89 d2 7e 26 37 ......Microsoft Wi-Fi Direct Virtual Adapter #2
 17...f8 89 d2 7e 26 38 ......Bluetooth Device (Personal Area Network)
  1...........................Software Loopback Interface 1
 16...00 15 5d 33 c0 77 ......Hyper-V Virtual Ethernet Adapter
 77...00 15 5d c0 9e 8b ......Hyper-V Virtual Ethernet Adapter #2
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.0.1    192.168.0.113     25
          0.0.0.0          0.0.0.0            在链路上        198.18.0.1      0
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
     172.23.208.0    255.255.240.0            在链路上      172.23.208.1   5256
     172.23.208.1  255.255.255.255            在链路上      172.23.208.1   5256
   172.23.223.255  255.255.255.255            在链路上      172.23.208.1   5256
      172.29.64.0    255.255.240.0            在链路上       172.29.64.1   5256
      172.29.64.1  255.255.255.255            在链路上       172.29.64.1   5256
    172.29.79.255  255.255.255.255            在链路上       172.29.64.1   5256
      192.168.0.0    255.255.255.0            在链路上     192.168.0.113    281
    192.168.0.113  255.255.255.255            在链路上     192.168.0.113    281
    192.168.0.255  255.255.255.255            在链路上     192.168.0.113    281
       198.18.0.0  255.255.255.252            在链路上        198.18.0.1    256
       198.18.0.1  255.255.255.255            在链路上        198.18.0.1    256
       198.18.0.3  255.255.255.255            在链路上        198.18.0.1    256
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上     192.168.0.113    281
        224.0.0.0        240.0.0.0            在链路上       172.29.64.1   5256
        224.0.0.0        240.0.0.0            在链路上      172.23.208.1   5256
        224.0.0.0        240.0.0.0            在链路上        198.18.0.1    256
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上     192.168.0.113    281
  255.255.255.255  255.255.255.255            在链路上       172.29.64.1   5256
  255.255.255.255  255.255.255.255            在链路上      172.23.208.1   5256
  255.255.255.255  255.255.255.255            在链路上        198.18.0.1    256
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
 15    281 ::/0                     fe80::3e6a:48ff:fe39:c277
 49      0 ::/0                     在链路上
  1    331 ::1/128                  在链路上
 15    281 fd00:3c6a:4839:c277::/64 在链路上
 15    281 fd00:3c6a:4839:c277::1007/128
                                    在链路上
 15    281 fd00:3c6a:4839:c277:6525:1eac:301:f859/128
                                    在链路上
 15    281 fd00:3c6a:4839:c277:c134:d474:8e2e:aea0/128
                                    在链路上
 49    256 fdfe:dcba:9876::/126     在链路上
 49    256 fdfe:dcba:9876::1/128    在链路上
 15    281 fe80::/64                在链路上
 16   5256 fe80::/64                在链路上
 77   5256 fe80::/64                在链路上
 16   5256 fe80::54f4:337a:935c:eb0c/128
                                    在链路上
 77   5256 fe80::5d5d:9993:a915:6214/128
                                    在链路上
 15    281 fe80::ebd9:d2cc:1ab1:2814/128
                                    在链路上
  1    331 ff00::/8                 在链路上
 15    281 ff00::/8                 在链路上
 16   5256 ff00::/8                 在链路上
 77   5256 ff00::/8                 在链路上
 49    256 ff00::/8                 在链路上
===========================================================================
永久路由:
  无
```
```

关闭Clash：
ainsc>  route print
===========================================================================
接口列表
 18...00 ff 5f 5f 72 2e ......Sangfor SSL VPN CS Support System VNIC
 25...f8 89 d2 7e 26 37 ......Hyper-V Virtual Ethernet Adapter #3
 15...f8 89 d2 7e 26 37 ......Hyper-V Virtual Ethernet Adapter #4
 26...fa 89 d2 7e 26 27 ......Microsoft Wi-Fi Direct Virtual Adapter
 27...fa 89 d2 7e 26 37 ......Microsoft Wi-Fi Direct Virtual Adapter #2
 17...f8 89 d2 7e 26 38 ......Bluetooth Device (Personal Area Network)
  1...........................Software Loopback Interface 1
 16...00 15 5d 33 c0 77 ......Hyper-V Virtual Ethernet Adapter
 77...00 15 5d c0 9e 8b ......Hyper-V Virtual Ethernet Adapter #2
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.0.1    192.168.0.113     25
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
     172.23.208.0    255.255.240.0            在链路上      172.23.208.1   5256
     172.23.208.1  255.255.255.255            在链路上      172.23.208.1   5256
   172.23.223.255  255.255.255.255            在链路上      172.23.208.1   5256
      172.29.64.0    255.255.240.0            在链路上       172.29.64.1   5256
      172.29.64.1  255.255.255.255            在链路上       172.29.64.1   5256
    172.29.79.255  255.255.255.255            在链路上       172.29.64.1   5256
      192.168.0.0    255.255.255.0            在链路上     192.168.0.113    281
    192.168.0.113  255.255.255.255            在链路上     192.168.0.113    281
    192.168.0.255  255.255.255.255            在链路上     192.168.0.113    281
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上     192.168.0.113    281
        224.0.0.0        240.0.0.0            在链路上       172.29.64.1   5256
        224.0.0.0        240.0.0.0            在链路上      172.23.208.1   5256
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上     192.168.0.113    281
  255.255.255.255  255.255.255.255            在链路上       172.29.64.1   5256
  255.255.255.255  255.255.255.255            在链路上      172.23.208.1   5256
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
 15    281 ::/0                     fe80::3e6a:48ff:fe39:c277
  1    331 ::1/128                  在链路上
 15    281 fd00:3c6a:4839:c277::/64 在链路上
 15    281 fd00:3c6a:4839:c277::1007/128
                                    在链路上
 15    281 fd00:3c6a:4839:c277:6525:1eac:301:f859/128
                                    在链路上
 15    281 fd00:3c6a:4839:c277:c134:d474:8e2e:aea0/128
                                    在链路上
 15    281 fe80::/64                在链路上
 16   5256 fe80::/64                在链路上
 77   5256 fe80::/64                在链路上
 16   5256 fe80::54f4:337a:935c:eb0c/128
                                    在链路上
 77   5256 fe80::5d5d:9993:a915:6214/128
                                    在链路上
 15    281 fe80::ebd9:d2cc:1ab1:2814/128
                                    在链路上
  1    331 ff00::/8                 在链路上
 15    281 ff00::/8                 在链路上
 16   5256 ff00::/8                 在链路上
 77   5256 ff00::/8                 在链路上
===========================================================================
永久路由:
  无
```

Clash配置和docker route：（用的是网站别人分享的：https://myuan.fun/rang-docker-easyconnect-yu-clash-he-ping-gong-chu/）
```

mode: rule
mixed-port: 7890
external-controller: 127.0.0.1:19953
secret: 4616077c-8348-40f7-b29e-dd3aeb78595f
proxy-providers:
  机场提供器:
    type: http
    path: "./ruleset/westworld.yaml"
    url: "<订阅地址>"
    health-check:
      enable: 
mode: rule
mixed-port: 7890
external-controller: 127.0.0.1:19953
secret: 4616077c-8348-40f7-b29e-dd3aeb78595f
proxy-providers:
  机场提供器:
    type: http
    path: "./ruleset/westworld.yaml"
    url: "<订阅地址>"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxies:
  - { 
      type: socks5, name: "easyconnect_vpn", server: "127.0.0.1", port: '1080'
    }
proxy-groups:
  - { name: 机场, type: url-test, use: [机场提供器] }
rules:
  - IP-CIDR,192.168.0.0/24,easyconnect_vpn
  - IP-CIDR,192.168.0.115/32,easyconnect_vpn
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,机场
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,机场
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,机场

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxies:
  - { 
      type: socks5, name: "easyconnect_vpn", server: "127.0.0.1", port: '1080'
    }
proxy-groups:
  - { name: 机场, type: url-test, use: [机场提供器] }
rules:
  - IP-CIDR,192.168.0.0/24,easyconnect_vpn
  - IP-CIDR,192.168.0.115/32,easyconnect_vpn
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,机场
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,机场
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,机场

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

```
docker中 ip rule信息：
```
2024-05-10 15:15:39 [2024-05-10 07:15:16][E][ 169][ConnectDomainSock][cms] /usr/share/sangfor/EasyConnect/resources/conf/ECDomainFile domain socket connect failed, errno:2, errstr:No such file or directory.

# ip route
default via 172.17.0.1 dev eth0 
2.0.1.0/24 dev tun0 proto kernel scope link src 2.0.1.8 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2 
192.168.0.35 dev tun0 scope link 
192.168.0.115 dev tun0 scope link 
192.168.0.179 dev tun0 scope link 
# ip rule
0:      from all lookup local
32760:  from all iif lo sport 5901 lookup 2
32761:  from all iif lo sport 1080 lookup 2
32762:  from all iif lo sport 4440 lookup 2
32763:  from all iif lo sport 20000 lookup 2
32764:  from all iif lo sport 54530 lookup 2
32765:  from all iif lo sport 8888 lookup 2
32766:  from all lookup main
32767:  from all lookup default
```
