### ISSUE TITLE
间隔一段时间就会无法连接容器

### ISSUE THREAD

**Issue by fjk0618** [docker-easyconnect/docker-easyconnect#405]
MAC电脑，用的docker compose启动。过一阵子vnc就连接不上了，需要使用docker restart容器后才能正常连接，每天都要重启容器好奔溃
<details>
<summary>docker-compose.yml</summary>
version: '3.8'
```
services:
  #202.100.241.27
  inter:
    image: hagb/docker-easyconnect:7.6.7
    container_name: inter
    environment:
      #vnc密码
      - PASSWORD=admin
      - URLWIN=1
      - DISABLE_PKG_VERSION_XML=1
    volumes:
      - $HOME/.ecdata:/root
    ports:
      #vnc端口号
      - "15901:5901"
      #sockets5代理
      - "11080:1080"
      #http代理
      - "11081:8888"
      #网页登录端口
      - "54531:54530"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          memory: 500M
  #202.100.241.14
  intra:
    image: hagb/docker-easyconnect:7.6.7
    container_name: intra
    environment:
      #vnc密码
      - PASSWORD=admin
      - URLWIN=1
      - DISABLE_PKG_VERSION_XML=1
    volumes:
      - $HOME/.ecdata:/root
    ports:
      #vnc端口号
      - "25901:5901"
      #sockets5代理
      - "21080:1080"
      #http代理
      - "21081:8888"
      #网页登录端口
      - "54532:54530"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          memory: 500M
```
</details>
