### ISSUE TITLE
更新docker 28.0.0后VNC访问黑屏，无法登录

### ISSUE THREAD

**Issue by hv0905** [docker-easyconnect/docker-easyconnect#425]
Docker compose 文件：
```yaml
services:
  easyconnect:
    image: hagb/docker-easyconnect:7.6.7
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      PASSWORD: ******
      URLWIN: "1"
    volumes:
      - /mnt/star/docker/volumes/easyconnect/root:/root
    ports:
      - "0.0.0.0:25901:5901"
      - "0.0.0.0:21080:1080"
        #      - "0.0.0.0:28888:8888"
        #    tty: true
        #    stdin_open: true
  curl_service:
    image: curlimages/curl:latest
    depends_on:
      - easyconnect
    entrypoint: >
      /bin/sh -c "while true; do
        curl -x socks5h://easyconnect:1080 https://[内网地址];
        sleep 60;
      done"
```

![Image](https://github.com/user-attachments/assets/5731a688-0ffb-4982-a4c8-ca3e5263e9c0)

容器启动后VNC访问黑屏，无法显示登陆界面，log输出：

![Image](https://github.com/user-attachments/assets/6e67adb5-1344-46f6-a315-6d4dd0ab29d0)

volume目录清空后重启问题依旧。

最近做过的唯一变更就是dockerd更新到了v28.0.0, apt不太方便降级, 不知道有没有workaround...

**Comment by fly6516** [comment]
这个确实是docker更新导致的问题
你可以先尝试在compose添加
```
    security_opt:
      - seccomp=unconfined
```
你可以先尝试能否可用，具体修复可能暂时无法完成
完整修改例子如下：
```
services:
  easyconnect:
    image: hagb/docker-easyconnect:7.6.7
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
    environment:
      PASSWORD: ******
      URLWIN: "1"
    volumes:
      - /mnt/star/docker/volumes/easyconnect/root:/root
    ports:
      - "0.0.0.0:25901:5901"
      - "0.0.0.0:21080:1080"
        #      - "0.0.0.0:28888:8888"
        #    tty: true
        #    stdin_open: true
  curl_service:
    image: curlimages/curl:latest
    depends_on:
      - easyconnect
    entrypoint: >
      /bin/sh -c "while true; do
        curl -x socks5h://easyconnect:1080 https://[内网地址];
        sleep 60;
      done"
```
